name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build for x86_64
      run: cargo build --verbose
    - name: Build for Aarch64
      run: cargo build --target aarch64-unknown-uefi-msvc.json
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: target
        path: target
