name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add rust-src
      run: rustup component add rust-src
    - name: Build for x86_64
      run: cargo build --verbose
    - name: Upload the target directory
      uses: actions/upload-artifact@v2.2.2
      with:
        name: target
        path: target

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add rust-src
        run: rustup component add rust-src
      - name: Build for Aarch64
        run: cargo build --verbose --target aarch64-unknown-uefi-msvc.json
      - name: Upload the target directory
        uses: actions/upload-artifact@v2.2.2
        with:
          name: target
          path: target
